#
# gh-pages.yaml
#

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master #
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Install project dependencies
        run: |
          echo "Installing project dependencies..."
          yarn install

      - name: Build project
        run: |
          echo "Building project..."
          yarn build

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy
        run: |
          echo "Deploying project to gh-pages..."
          yarn deploy

      - name: Show build output
        run: |
          echo ""
          echo "Repository:"
          pwd

          echo ""
          echo "Files:"
          ls -lah
          echo ""

          echo ""
          echo "Build directory:"
          ls -lah build || true
          echo ""

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: |
            build
